@TM:1136906833
@N:  :"":0:0:0:-1|Only System clock will be Autoconstrained
@TM:1136906934
@N: FX164 :"":0:0:0:-1|The option to pack flops in the IOB has not been specified 
@TM:1136906833
@N: MT195 :"":0:0:0:-1|This timing report estimates place and route data. Please look at the place and route timing report for final timing..
@N: MT197 :"":0:0:0:-1|Clock constraints cover only FF-to-FF paths associated with the clock..
@N: MT204 :"":0:0:0:-1|Autoconstrain Mode is ON
@TM:1136906832
@N:  :"c:\prj\example-4-5\mux.v":1:7:1:9|Synthesizing module mux
